baseURL: http://your-website-here.lan
languageCode: en-us
paginate: 6
theme: hugo-service-industry
title: hugo-service-industry
menu:
  Main:
    - name: Exhibition
      url: "#gallery"
      weight: 1
    - name: Feature
      url: "#service"
      weight: 1
    - name: About
      url: /about/
      weight: 3
    - name: Blog
      url: "#blog"
      weight: 4
    - name: Pricing
      url: "#pricing"
      weight: 5
    - name: FAQ
      url: "#faq"
      weight: 6
    - name: Contact
      url: "#contact"
      weight: 7
  sitemap:
    - name: Privacy Policy
      url: /privacy/
      weight: 1
    - name: Terms
      url: /terms/
      weight: 2
params:
  copyright: © {year} your-website-here.lan
  googleAnalytics: G-9999999999
  logo: images/logo.png
  footerlogo: images/logo.png
  footerDescription: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Odit quia ab, natus fugiat voluptas saepe ipsum animi officiis in molestiae?
  address:
    address: 115 W 18th St. <br>  New York, NY 10011
    email: hello@example.com
    openingDesc: Give us a call or drop by anytime, we endeavour to answer all
      enquiries within 24 hours on business days.
    openingHours: We are open from 7am — 7pm week days.
    phone: +(448) 833 5272 332
    fax: +(448) 833 5272 332
  map:
    APIkey: AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0
    latitude: "45.4502528"
    longitude: "-122.783407"
  social:
    - icon: ti-facebook
      url: https://www.facebook.com/
      weight: 1
    - icon: ti-twitter-alt
      url: https://twitter.com/
      weight: 2
    - icon: ti-dribbble
      url: https://dribbble.com/
      weight: 3
    - icon: ti-instagram
      url: https://www.instagram.com/
      weight: 4
